version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: aircargo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aircargo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ashutosh1503k
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: aircargo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  prometheus:
    image: prom/prometheus
    container_name: aircargo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: aircargo-grafana
    ports:
      - "3002:3000"

volumes:
  pgdata:
  redisdata: