spring:
  datasource:
    url: jdbc:postgresql://<NEON_HOST>:<NEON_PORT>/<NEON_DB>?options=-c%20TimeZone=UTC
    username: <NEON_USER>
    password: <NEON_PASSWORD>
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.time_zone: UTC

  redis:
    redisson:
      config: classpath:redisson.yml   # <-- just points to the file

  cache:
    type: redis

  flyway:
    enabled: true
    url: jdbc:postgresql://<NEON_HOST>:<NEON_PORT>/<NEON_DB>?options=-c%20TimeZone=UTC
    user: <NEON_USER>
    password: <NEON_PASSWORD>
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

management:
  endpoints:
    prometheus: true
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  cache:
    ttl:
      route: PT15M
      flight: PT30M
